version: '3.8'

services:
  whisper:
    build: ./src/python
    container_name: faster-whisper
    ports:
      - '5566:5566'
    environment:
      - MODEL_SIZE=small
      - DEVICE=cpu 
    restart: unless-stopped
